/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSmeWebPresenceRouteImport } from './routes/services.sme-web-presence'
import { Route as ServicesProPresenceRouteImport } from './routes/services.pro-presence'
import { Route as ServicesCustomSoftwareRouteImport } from './routes/services.custom-software'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSmeWebPresenceRoute = ServicesSmeWebPresenceRouteImport.update({
  id: '/services/sme-web-presence',
  path: '/services/sme-web-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProPresenceRoute = ServicesProPresenceRouteImport.update({
  id: '/services/pro-presence',
  path: '/services/pro-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomSoftwareRoute = ServicesCustomSoftwareRouteImport.update({
  id: '/services/custom-software',
  path: '/services/custom-software',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/labs': typeof LabsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/pro-presence': typeof ServicesProPresenceRoute
  '/services/sme-web-presence': typeof ServicesSmeWebPresenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/labs': typeof LabsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/pro-presence': typeof ServicesProPresenceRoute
  '/services/sme-web-presence': typeof ServicesSmeWebPresenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/labs': typeof LabsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/pro-presence': typeof ServicesProPresenceRoute
  '/services/sme-web-presence': typeof ServicesSmeWebPresenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/labs'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/custom-software'
    | '/services/pro-presence'
    | '/services/sme-web-presence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/labs'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/custom-software'
    | '/services/pro-presence'
    | '/services/sme-web-presence'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/labs'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/custom-software'
    | '/services/pro-presence'
    | '/services/sme-web-presence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  LabsRoute: typeof LabsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesCustomSoftwareRoute: typeof ServicesCustomSoftwareRoute
  ServicesProPresenceRoute: typeof ServicesProPresenceRoute
  ServicesSmeWebPresenceRoute: typeof ServicesSmeWebPresenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sme-web-presence': {
      id: '/services/sme-web-presence'
      path: '/services/sme-web-presence'
      fullPath: '/services/sme-web-presence'
      preLoaderRoute: typeof ServicesSmeWebPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pro-presence': {
      id: '/services/pro-presence'
      path: '/services/pro-presence'
      fullPath: '/services/pro-presence'
      preLoaderRoute: typeof ServicesProPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-software': {
      id: '/services/custom-software'
      path: '/services/custom-software'
      fullPath: '/services/custom-software'
      preLoaderRoute: typeof ServicesCustomSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  LabsRoute: LabsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesCustomSoftwareRoute: ServicesCustomSoftwareRoute,
  ServicesProPresenceRoute: ServicesProPresenceRoute,
  ServicesSmeWebPresenceRoute: ServicesSmeWebPresenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
